/*
 * Copyright (C) 2018 askaeks
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package restaurant.frames;

import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import restaurant.dialogs.KasirDialog;
import restaurant.dialogs.MenuDialog;
import restaurant.dialogs.PelayanNewDialog;
import restaurant.dialogs.TableNewDialog;
import restaurant.models.KasirModel;
import restaurant.models.MenuModel;
import restaurant.models.OrderAdminModel;
import restaurant.models.PelayanModel;
import restaurant.models.PesananAdminModel;
import restaurant.models.TableModel;
import restaurant.objects.KasirObject;
import restaurant.objects.MenuObject;
import restaurant.objects.PelayanObject;
import restaurant.objects.TableObject;
import restaurant.states.ApplicationState;

/**
 *
 * @author askaeks
 */
public class Admin extends javax.swing.JFrame {
    
    /**
     * Model definition
     */
    private final TableModel modelTable = new TableModel();
    private final PelayanModel modelPelayan = new PelayanModel();
    private final KasirModel modelKasir = new KasirModel();
    private final MenuModel modelMenu = new MenuModel();
    private final OrderAdminModel modelOrderAdmin = new OrderAdminModel();
    private final PesananAdminModel modelPesananAdmin = new PesananAdminModel();
    
    /**
     * Creates new form Administrator
     * @param pFrame
     */
    public Admin(JFrame pFrame) {
     
        if (pFrame != null) {
            this.setLocationRelativeTo(pFrame);
            pFrame.dispose();
        }
        
        initComponents();
        
        tblTables.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            // do some actions here, for example
            // print first column value from selected row
            if (event.getValueIsAdjusting() == false) {
                btnTablesDelete.setEnabled(true);
            }
        });
        
        tblPelayan.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            // do some actions here, for example
            // print first column value from selected row
            if (event.getValueIsAdjusting() == false) {
                btnHapusPelayan.setEnabled(true);
            }
        });
        
        tblKasir.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            // do some actions here, for example
            // print first column value from selected row
            if (event.getValueIsAdjusting() == false) {
                btnHapusKasir.setEnabled(true);
                btnEditKasir.setEnabled(true);
                btnReset.setEnabled(true);
            }
        });
        
        tblMenu.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            // do some actions here, for example
            // print first column value from selected row
            if (event.getValueIsAdjusting() == false) {
                btnHapusMenu.setEnabled(true);
                btnEditMenu.setEnabled(true);
                btnEditStock.setEnabled(true);
            }
        });
        
        tblMenu.getColumnModel().getColumn(0).setPreferredWidth(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesanansaya = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblPenjualanAdmin = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKasir = new javax.swing.JTable();
        btnTambahKasir = new javax.swing.JButton();
        btnHapusKasir = new javax.swing.JButton();
        btnEditKasir = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPelayan = new javax.swing.JTable();
        btnTambahPelayan = new javax.swing.JButton();
        btnHapusPelayan = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        btnHidanganPembuka = new javax.swing.JButton();
        btnHidanganUtama = new javax.swing.JButton();
        btnHidanganPenutup = new javax.swing.JButton();
        btnMinuman = new javax.swing.JButton();
        btnTambahMenu = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        btnHapusMenu = new javax.swing.JButton();
        btnEditMenu = new javax.swing.JButton();
        btnEditStock = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMenu = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        panelTables = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTables = new javax.swing.JTable();
        btnTableAdd = new javax.swing.JButton();
        btnTablesDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Order Management System - Admin");
        setResizable(false);

        tblPesanansaya.setModel(modelOrderAdmin);
        jScrollPane1.setViewportView(tblPesanansaya);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Pesanan", jPanel8);

        tblPenjualanAdmin.setModel(modelPesananAdmin);
        jScrollPane7.setViewportView(tblPenjualanAdmin);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Penjualan Item", jPanel9);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Riwayat", jPanel2);

        tblKasir.setModel(modelKasir);
        tblKasir.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblKasir);

        btnTambahKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/add.png"))); // NOI18N
        btnTambahKasir.setText("Tambah Kasir");
        btnTambahKasir.setIconTextGap(5);
        btnTambahKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahKasirActionPerformed(evt);
            }
        });

        btnHapusKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/garbage.png"))); // NOI18N
        btnHapusKasir.setEnabled(false);
        btnHapusKasir.setIconTextGap(5);
        btnHapusKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKasirActionPerformed(evt);
            }
        });

        btnEditKasir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/edit.png"))); // NOI18N
        btnEditKasir.setEnabled(false);
        btnEditKasir.setIconTextGap(5);
        btnEditKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditKasirActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/refresh-button.png"))); // NOI18N
        btnReset.setEnabled(false);
        btnReset.setIconTextGap(5);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/cashier-2.png"))); // NOI18N
        jLabel1.setText("Manage Kasir");
        jLabel1.setIconTextGap(10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambahKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapusKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapusKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambahKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditKasir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kasir", jPanel3);

        tblPelayan.setModel(modelPelayan);
        tblPelayan.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tblPelayan);

        btnTambahPelayan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/add.png"))); // NOI18N
        btnTambahPelayan.setText("Tambah Pelayan");
        btnTambahPelayan.setIconTextGap(5);
        btnTambahPelayan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahPelayanActionPerformed(evt);
            }
        });

        btnHapusPelayan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/garbage.png"))); // NOI18N
        btnHapusPelayan.setText("Hapus Pelayan");
        btnHapusPelayan.setEnabled(false);
        btnHapusPelayan.setIconTextGap(5);
        btnHapusPelayan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPelayanActionPerformed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/businessman-3.png"))); // NOI18N
        jLabel13.setText("Manage Pelayan");
        jLabel13.setIconTextGap(10);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(btnTambahPelayan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapusPelayan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHapusPelayan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(btnTambahPelayan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pelayan", jPanel4);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Tambah Menu"));

        btnHidanganPembuka.setText("Hidangan Pembuka");
        btnHidanganPembuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHidanganPembukaActionPerformed(evt);
            }
        });

        btnHidanganUtama.setText("Hidangan Utama");
        btnHidanganUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHidanganUtamaActionPerformed(evt);
            }
        });

        btnHidanganPenutup.setText("Hidangan Penutup");
        btnHidanganPenutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHidanganPenutupActionPerformed(evt);
            }
        });

        btnMinuman.setText("Minuman");
        btnMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinumanActionPerformed(evt);
            }
        });

        btnTambahMenu.setText("Tambah Menu");
        btnTambahMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHidanganPembuka, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHidanganUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHidanganPenutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMinuman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTambahMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHidanganPembuka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHidanganUtama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHidanganPenutup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinuman)
                .addGap(12, 12, 12))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Opsi"));

        btnHapusMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/garbage.png"))); // NOI18N
        btnHapusMenu.setEnabled(false);
        btnHapusMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMenuActionPerformed(evt);
            }
        });

        btnEditMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/edit.png"))); // NOI18N
        btnEditMenu.setEnabled(false);
        btnEditMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMenuActionPerformed(evt);
            }
        });

        btnEditStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/warehouse.png"))); // NOI18N
        btnEditStock.setEnabled(false);
        btnEditStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHapusMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditStock, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapusMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditStock, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblMenu.setModel(modelMenu);
        tblMenu.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tblMenu);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/fast-food.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(70, 70, 70)))
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Menu", jPanel5);

        tblTables.setModel(modelTable);
        tblTables.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tblTables);

        btnTableAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/add.png"))); // NOI18N
        btnTableAdd.setText("Tambah Meja");
        btnTableAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableAddActionPerformed(evt);
            }
        });

        btnTablesDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/garbage.png"))); // NOI18N
        btnTablesDelete.setText("Hapus Meja");
        btnTablesDelete.setEnabled(false);
        btnTablesDelete.setIconTextGap(5);
        btnTablesDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablesDeleteActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/chair.png"))); // NOI18N
        jLabel2.setText("Manage Tables");
        jLabel2.setIconTextGap(10);

        javax.swing.GroupLayout panelTablesLayout = new javax.swing.GroupLayout(panelTables);
        panelTables.setLayout(panelTablesLayout);
        panelTablesLayout.setHorizontalGroup(
            panelTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                    .addGroup(panelTablesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTableAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTablesDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTablesLayout.setVerticalGroup(
            panelTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTableAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTablesDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Tables", panelTables);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/enter.png"))); // NOI18N
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(690, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Operasi", jPanel14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTableAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableAddActionPerformed
        TableNewDialog dialog = new TableNewDialog(this, true);
       
        dialog.setVisible(true);
        
        // if dialog saved clicked
        if (dialog != (null)) {
            if (dialog.isSaved) {
                TableObject toSave = new TableObject(dialog.kode, dialog.lokasi);

                modelTable.add(toSave);
            }
        }
    }//GEN-LAST:event_btnTableAddActionPerformed

    private void btnTablesDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablesDeleteActionPerformed
        if (!tblTables.getSelectionModel().isSelectionEmpty()) {
            TableObject tbRemove = modelTable.remove(tblTables.getSelectedRow());
            
            if (tbRemove != null) {
                btnTablesDelete.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnTablesDeleteActionPerformed

    private void btnTambahPelayanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahPelayanActionPerformed
        PelayanNewDialog dialog = new PelayanNewDialog(this, true);
        
        dialog.setVisible(true);
        
        // if dialog saved clicked
        if (dialog != (null)) {
            if (dialog.isSaved) {
                PelayanObject toSave = new PelayanObject(dialog.kode, dialog.nama);

                modelPelayan.add(toSave);
            }
        }
    }//GEN-LAST:event_btnTambahPelayanActionPerformed

    private void btnHapusPelayanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPelayanActionPerformed
        if (!tblPelayan.getSelectionModel().isSelectionEmpty()) {
            PelayanObject tbRemove = modelPelayan.remove(tblPelayan.getSelectedRow());
            
            if (tbRemove != null) {
                btnHapusPelayan.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnHapusPelayanActionPerformed

    private void btnTambahKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahKasirActionPerformed
        KasirDialog dialog = new KasirDialog(this, true, null);
        
        dialog.setVisible(true);
        
        if (dialog != (null)) {
            if (dialog.isSaved) {
                KasirObject toSave = new KasirObject(dialog.nama, dialog.username, dialog.password, null);
                
                modelKasir.add(toSave);
            }
        }
    }//GEN-LAST:event_btnTambahKasirActionPerformed

    private void btnHapusKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKasirActionPerformed
        if (!tblKasir.getSelectionModel().isSelectionEmpty()) {
            KasirObject tbRemove = modelKasir.remove(tblKasir.getSelectedRow());
            
            if (tbRemove != null) {
                btnHapusKasir.setEnabled(false);
                btnEditKasir.setEnabled(false);
                btnReset.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnHapusKasirActionPerformed

    private void btnEditKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditKasirActionPerformed
        if (!tblKasir.getSelectionModel().isSelectionEmpty()) {
            Integer selectedRow = tblKasir.getSelectedRow();
            
            KasirObject tobeEdit = modelKasir.get(selectedRow);
            
            KasirDialog dialog = new KasirDialog(this, true, tobeEdit);
            
            dialog.setVisible(true);
            
            if (dialog.isEdit && dialog.isSaved) {
                KasirObject toUpdate = new KasirObject(dialog.nama, dialog.username, dialog.password, null);
                
                modelKasir.update(selectedRow, toUpdate);
            }
        }
    }//GEN-LAST:event_btnEditKasirActionPerformed
    
    private void createMenu(MenuDialog menu) {
        MenuObject toSave = new MenuObject(menu.id, menu.nama, menu.kategori, menu.harga, menu.stock);
        
        modelMenu.add(toSave);
    }
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        tblKasir.getSelectionModel().clearSelection();
        
        btnEditKasir.setEnabled(false);
        btnHapusKasir.setEnabled(false);
        btnReset.setEnabled(false);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnTambahMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMenuActionPerformed
        MenuDialog dialog = new MenuDialog(this, true, -1, null);
        
        dialog.setVisible(true);
        
        if (dialog != (null) && dialog.isSaved) {
            createMenu(dialog);
        }
    }//GEN-LAST:event_btnTambahMenuActionPerformed

    private void btnHidanganPembukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHidanganPembukaActionPerformed
        MenuDialog dialog = new MenuDialog(this, true, 0, null);
        
        dialog.setVisible(true);
        
        if (dialog != (null) && dialog.isSaved) {
            createMenu(dialog);
        }
    }//GEN-LAST:event_btnHidanganPembukaActionPerformed

    private void btnHidanganUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHidanganUtamaActionPerformed
        MenuDialog dialog = new MenuDialog(this, true, 1, null);
        
        dialog.setVisible(true);
        
        if (dialog != (null) && dialog.isSaved) {
            createMenu(dialog);
        }
    }//GEN-LAST:event_btnHidanganUtamaActionPerformed

    private void btnHidanganPenutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHidanganPenutupActionPerformed
        MenuDialog dialog = new MenuDialog(this, true, 2, null);
        
        dialog.setVisible(true);
        
        if (dialog != (null) && dialog.isSaved) {
            createMenu(dialog);
        }
    }//GEN-LAST:event_btnHidanganPenutupActionPerformed

    private void btnMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinumanActionPerformed
        MenuDialog dialog = new MenuDialog(this, true, 3, null);
        
        dialog.setVisible(true);
        
        if (dialog != (null) && dialog.isSaved) {
            createMenu(dialog);
        }
    }//GEN-LAST:event_btnMinumanActionPerformed

    private void btnHapusMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMenuActionPerformed
        if (!tblMenu.getSelectionModel().isSelectionEmpty()) {
            MenuObject tbRemove = modelMenu.remove(tblMenu.getSelectedRow());
            
            if (tbRemove != null) {
                btnHapusMenu.setEnabled(false);
                btnEditMenu.setEnabled(false);
                btnEditStock.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnHapusMenuActionPerformed

    private void btnEditMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMenuActionPerformed
        if (!tblMenu.getSelectionModel().isSelectionEmpty()) {
            Integer selectedRow = tblMenu.getSelectedRow();
            
            MenuObject tobeEdit = modelMenu.get(selectedRow);
            
            MenuDialog dialog = new MenuDialog(this, true, -1, tobeEdit);
            
            dialog.setVisible(true);
            
            if (dialog.isSaved && dialog.isEdit) {
                MenuObject toUpdate = new MenuObject(dialog.id, dialog.nama, dialog.kategori, dialog.harga, dialog.stock);

                modelMenu.update(selectedRow, toUpdate);
            }
        }
    }//GEN-LAST:event_btnEditMenuActionPerformed

    private void btnEditStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditStockActionPerformed
        if (!tblMenu.getSelectionModel().isSelectionEmpty()) {
            Integer selectedRow = tblMenu.getSelectedRow();
            
            MenuObject toEditStock = modelMenu.get(selectedRow);
            
            toEditStock.setStock(!toEditStock.getStock());
            
            modelMenu.update(selectedRow, toEditStock);
        } else {
        }
    }//GEN-LAST:event_btnEditStockActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ApplicationState.logout();
        
        new Masuk(this).setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditKasir;
    private javax.swing.JButton btnEditMenu;
    private javax.swing.JButton btnEditStock;
    private javax.swing.JButton btnHapusKasir;
    private javax.swing.JButton btnHapusMenu;
    private javax.swing.JButton btnHapusPelayan;
    private javax.swing.JButton btnHidanganPembuka;
    private javax.swing.JButton btnHidanganPenutup;
    private javax.swing.JButton btnHidanganUtama;
    private javax.swing.JButton btnMinuman;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTableAdd;
    private javax.swing.JButton btnTablesDelete;
    private javax.swing.JButton btnTambahKasir;
    private javax.swing.JButton btnTambahMenu;
    private javax.swing.JButton btnTambahPelayan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JPanel panelTables;
    private javax.swing.JTable tblKasir;
    private javax.swing.JTable tblMenu;
    private javax.swing.JTable tblPelayan;
    private javax.swing.JTable tblPenjualanAdmin;
    private javax.swing.JTable tblPesanansaya;
    private javax.swing.JTable tblTables;
    // End of variables declaration//GEN-END:variables
}
