/*
 * Copyright (C) 2018 askaeks
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package restaurant.frames;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.event.ListSelectionEvent;
import restaurant.dialogs.PesananDialog;
import restaurant.dialogs.PesananExtendDialog;
import restaurant.models.OrderKasirModel;
import restaurant.objects.KasirObject;
import restaurant.objects.MenuObject;
import restaurant.objects.OrderObject;
import restaurant.states.ApplicationState;

/**
 *
 * @author askaeks
 */
public class Kasir extends javax.swing.JFrame {
    
    private final String username;
    
    private final OrderKasirModel modelOrderKasir = new OrderKasirModel();
    
    /**
     * Creates new form Cashier
     * @param pFrame
     */
    public Kasir(JFrame pFrame) {
        
        this.setLocationRelativeTo(pFrame);
        pFrame.dispose();
        
        username = ApplicationState.getUsername();
        
        initComponents();
        
        tblPesanan.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            // do some actions here, for example
            // print first column value from selected row
            if (event.getValueIsAdjusting() == false) {
                btnSelengkapnya.setEnabled(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tblTambahPesanan = new javax.swing.JButton();
        btnSelengkapnya = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPesanan = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Order Management System - Kasir");
        setResizable(false);

        tblTambahPesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/add.png"))); // NOI18N
        tblTambahPesanan.setText("Tambah Pesanan");
        tblTambahPesanan.setIconTextGap(5);
        tblTambahPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblTambahPesananActionPerformed(evt);
            }
        });

        btnSelengkapnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/more.png"))); // NOI18N
        btnSelengkapnya.setText("Lihat Lengkap");
        btnSelengkapnya.setEnabled(false);
        btnSelengkapnya.setIconTextGap(5);
        btnSelengkapnya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelengkapnyaActionPerformed(evt);
            }
        });

        tblPesanan.setModel(modelOrderKasir);
        jScrollPane2.setViewportView(tblPesanan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSelengkapnya, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                        .addComponent(tblTambahPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tblTambahPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSelengkapnya, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        jTabbedPane1.addTab("Riwayat Pesanan", jPanel1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/images/enter.png"))); // NOI18N
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(511, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Help", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTambahPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblTambahPesananActionPerformed
        PesananDialog dialog = new PesananDialog(this, true);
        
        dialog.setVisible(true);
        
        if (dialog != (null)) {
            if (dialog.isSaved) {
                
                OrderObject o = new OrderObject(null, dialog.meja, dialog.pelayan, new KasirObject(null, ApplicationState.getUsername(), null, null), dialog.totalHarga);
                
                modelOrderKasir.add(o, dialog.selectedMenu);
                
            }
        }
    }//GEN-LAST:event_tblTambahPesananActionPerformed

    private String rupiah(Integer rupiah) {
        return NumberFormat.getCurrencyInstance(new Locale("id", "ID")).format(rupiah);
    }
    
    private void btnSelengkapnyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelengkapnyaActionPerformed
        if (!tblPesanan.getSelectionModel().isSelectionEmpty()) {
            OrderObject order = modelOrderKasir.get(tblPesanan.getSelectedRow());
            
            StringBuilder stringOutput = new StringBuilder();
            
            stringOutput.append("========== INFO ==========\n");
            stringOutput.append("Nomor\t: ").append(order.getIdPesanan()).append("\n");
            stringOutput.append("Pelayan\t: ").append(order.getPelayan().getNama()).append("\n");
            stringOutput.append("Meja\t: ").append(order.getMeja().getKode()).append("\n");
            stringOutput.append("========== PESANAN ==========\n");
            
            Integer i = 0;
            
            for (MenuObject m : order.getMenuList()) {
                stringOutput.append(++i).append(". ").append(m.getNama()).append("\n");
            }
            
            stringOutput.append("========== PEMBAYARAN ==========\n");
            stringOutput.append("Total Harga\t: ").append(rupiah(order.getHarga()));
            stringOutput.append("\n\nTerima kasih telah membeli produk kami.\n");
            stringOutput.append("========== TERIMA KASIH ==========\n");
            
            PesananExtendDialog pes = new PesananExtendDialog(this, true, stringOutput.toString());
            
            pes.setVisible(true);
        }
    }//GEN-LAST:event_btnSelengkapnyaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ApplicationState.logout();
        
        new Masuk(this).setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelengkapnya;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblPesanan;
    private javax.swing.JButton tblTambahPesanan;
    // End of variables declaration//GEN-END:variables
}
